name: 'rust-cargo-udeps'
description: 'Detect unused dependencies in a rust project'
author: 'Aaron Griffin'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  version:
    description: 'The version of cargo-udeps to install'
    required: true
    default: 'latest'
  target:
    description:  'Binary target to download'
    required: true
    default: 'x86_64-unknown-linux-gnu'
  args:
    required: false
    description: 'Extra command line arguments passed to cargo-udeps'
